name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        sudo apt install \
          build-essential \
          binutils-arm-none-eabi \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi
        pip install -r requirements.txt
    - name: Run notebooks
      run: |
        jupyter nbconvert --inplace --execute analyze/5_elmo.ipynb
